'use client';
import {useEffect,useRef,useState,ReactNode} from 'react';
import Link from './site-link';
import {ArrowUpRight,ArrowDown,Plus,Shield,Code2} from 'lucide-react';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import BrandLogo from './brand-logo';
import {rails,lifecycle,faq} from '../lib/content';

export function CinematicEntrance({enabled}:{enabled:boolean}){const [show,setShow]=useState(true);useEffect(()=>{const timer=setTimeout(()=>setShow(false),2100);return()=>clearTimeout(timer)},[]);if(!show||!enabled)return null;return <div className="cinema-entrance" aria-hidden="true"><div className="entrance-slice"/><div className="entrance-slice"/><div className="entrance-slice"/><div className="entrance-slice"/><div className="entrance-type"><span>R</span><span>E</span><span>L</span><span>L</span><span>O</span></div><div className="entrance-caption">MONEY, SET IN MOTION.</div></div>}
const Label=({children}:{children:ReactNode})=><div className="cinema-label"><i/>{children}</div>;
const Action=({href,children,outline=false}:{href:string;children:ReactNode;outline?:boolean})=><Link className={`cinema-action ${outline?'outline':''}`} href={href}><span>{children}</span><ArrowUpRight size={19}/></Link>;

export default function CinematicHome({enabled,privacy,code}:{enabled:boolean;privacy:ReactNode;code:ReactNode}){
 const root=useRef<HTMLDivElement>(null);const [step,setStep]=useState(0);const [usecase,setUsecase]=useState(0);
 useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const el=root.current;if(!el)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const context=gsap.context(()=>{
  if(!enabled||reduced){gsap.set('[data-cinema-reveal]',{opacity:1,y:0});return;}
  const hero=gsap.timeline({scrollTrigger:{trigger:'.cinema-hero',start:'top top',end:'bottom bottom',scrub:1}});
  hero.to('.hero-center-copy',{y:-35,opacity:0,ease:'none'},0).to('.hero-film',{scale:1.12,rotation:2,ease:'none'},0).to('.hero-bottom-line',{opacity:0},0);
  gsap.to('.reach-word',{xPercent:-22,ease:'none',scrollTrigger:{trigger:'.cinema-reach',start:'top bottom',end:'bottom top',scrub:1.4}});
  gsap.to('.rails-orbit',{rotation:-12,xPercent:8,ease:'none',scrollTrigger:{trigger:'.cinema-reach',start:'top bottom',end:'bottom top',scrub:1}});
  gsap.to('.lifecycle-film',{scale:1.4,rotation:-10,ease:'none',scrollTrigger:{trigger:'.cinema-lifecycle',start:'top top',end:'bottom bottom',scrub:1}});
  ScrollTrigger.create({trigger:'.cinema-lifecycle',start:'top top',end:'bottom bottom',onUpdate:s=>{setStep(Math.min(4,Math.floor(s.progress*5)));el.style.setProperty('--journey',String(s.progress));}});
  gsap.to('.privacy-word',{xPercent:15,ease:'none',scrollTrigger:{trigger:'.cinema-privacy',start:'top bottom',end:'bottom top',scrub:1}});
  gsap.to('.end-word',{scale:1.16,yPercent:-12,ease:'none',scrollTrigger:{trigger:'.cinema-end',start:'top bottom',end:'bottom bottom',scrub:1}});
  el.querySelectorAll('[data-cinema-reveal]').forEach(x=>gsap.fromTo(x,{y:65,opacity:.15},{y:0,opacity:1,duration:1.1,ease:'power3.out',scrollTrigger:{trigger:x,start:'top 92%',once:true}}));
 },el);return()=>context.revert();},[enabled]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{const video=entry.target as HTMLVideoElement;if(entry.isIntersecting&&enabled)video.play().catch(()=>{});else video.pause();}),{rootMargin:'100px'});root.current?.querySelectorAll('video').forEach(v=>{v.playbackRate=v.closest('.cinema-hero') ? 1 : 0.7;observer.observe(v);});return()=>observer.disconnect();},[enabled]);
 const scenarios=[['Rent. Handled.','An agent’s wallet. Your landlord’s Zelle.','$800 for October rent','Zelle'],['Work. Rewarded.','Pay the designer through the app they already use.','$240 for the brand identity','PayPal'],['Life. Settled.','Split dinner without making anyone learn a new wallet.','$36 for my share of dinner','Venmo'],['Time. Returned.','Let your agent take care of the everyday details.','$95 for the kitchen repair','Cash App']];
 return <div ref={root} className="cinematic-home">
 <div className="cinema-scroll-line" aria-hidden="true"/>
 <section className="cinema-hero" id="top"><div className="hero-stage"><div className="hero-film"><video src="/assets/cinema-vortex.mp4" poster="/assets/cinema-vortex.jpg" autoPlay muted loop playsInline preload="auto"/></div><div className="cinema-vignette"/><div className="hero-coordinates"><span>RELLO / 001</span><span>ONCHAIN → EVERYDAY</span></div><div className="hero-center-copy"><Label>THE LAST MILE OF AGENT MONEY</Label><h1>Agent money.<br/><em>Human reach.</em></h1><p>A payment layer on Robinhood Chain.<br/>From USDG to the apps people already use.</p><Action href="/agents">Put your agent to work</Action></div><div className="hero-bottom-line"><span>INTENT. CONNECTION. SETTLEMENT.</span><a href="#reach">SCROLL INTO THE SYSTEM <ArrowDown size={15}/></a><span>01 / 05</span></div></div></section>
 <section className="cinema-reach" id="reach"><div className="reach-atmosphere" aria-hidden="true"><div/><div/><div/></div><div className="reach-word" aria-hidden="true">THE LAST MILE.</div><div className="cinema-section-head"><Label>01 / BEYOND THE WALLET</Label><span>20 PAYMENT RAILS / ONE INTERFACE</span></div><div className="reach-story"><div><h2 data-cinema-reveal>Onchain money.<br/><em>Offchain life.</em></h2><p className="reach-intro" data-cinema-reveal>Your agent understands the task. A runner carries it into the real world. The recipient gets paid in a familiar app.</p></div><div className="reach-transmission" data-cinema-reveal><span>ONE INTENT / MANY DESTINATIONS</span><div><b>AGENT</b><i/><b>USDG</b><i/><b>RUNNER</b></div><p>The destination stays familiar.<br/>The connection changes everything.</p><strong>20<span>PAYMENT RAILS</span></strong></div></div><div className="rails-orbit" aria-hidden="true">{[rails.slice(0,7),rails.slice(7,14),rails.slice(14)].map((items,row)=><div className={`rail-current row-${row}`} key={row}><div>{[...items,...items].map((r,i)=><span key={i}><BrandLogo name={r}/>{r}<i>↗</i></span>)}</div></div>)}</div><div className="scenario-workspace" data-cinema-reveal><div className="scenario-nav" aria-label="Payment examples">{['Rent & bills','Creative work','Shared costs','Everyday services'].map((x,i)=><button className={i===usecase?'active':''} aria-pressed={i===usecase} onClick={()=>setUsecase(i)} key={x}><span>0{i+1}</span><BrandLogo name={scenarios[i][3]}/>{x}<ArrowUpRight size={16}/></button>)}</div><div className="scenario-copy" key={usecase}><div className="scenario-destination"><BrandLogo name={scenarios[usecase][3]}/><span>DESTINATION<em>{scenarios[usecase][3]}</em></span><strong>{scenarios[usecase][2].split(" ")[0]}</strong></div><span className="cinema-mono">EVERYDAY INTENT / 0{usecase+1}</span><h3>{scenarios[usecase][0]}</h3><p>{scenarios[usecase][1]}</p><Link href={'/agents?prompt='+encodeURIComponent('Pay '+scenarios[usecase][2]+' on '+scenarios[usecase][3])}>“Pay {scenarios[usecase][2]}”<ArrowUpRight size={24}/></Link></div></div></section>
 <section className={`cinema-lifecycle ${!enabled?'quiet-journey':''}`} id="how"><div className="lifecycle-stage"><video className="lifecycle-film" src="/assets/cinema-tunnel.mp4" poster="/assets/cinema-tunnel.jpg" muted loop playsInline preload="metadata"/><div className="lifecycle-shade"/><div className="cinema-section-head"><Label>02 / FOLLOW THE MONEY</Label><Link href="/docs/how-it-works">EXPLORE THE LIFECYCLE <ArrowUpRight size={16}/></Link></div><div className="journey-caption"><span>AN INTENTION BECOMES<br/>A HUMAN CONNECTION.</span><span>USDG / ROBINHOOD CHAIN</span></div>{enabled?<div className="journey-scene" key={step}><span className="journey-number" aria-hidden="true">0{step+1}</span><div className="journey-content"><span className="cinema-mono">{lifecycle[step][0].toUpperCase()} / {['AGENT','RUNNER','AGENT + ESCROW','RUNNER','SETTLEMENT'][step]}</span><h2>{lifecycle[step][1]}</h2><p>{lifecycle[step][2]}</p><span className="journey-rule"/></div></div>:<div className="quiet-steps">{lifecycle.map(([state,title,desc],i)=><article key={state}><span>0{i+1} / {state}</span><h3>{title}</h3><p>{desc}</p></article>)}</div>}<div className="journey-navigation">{lifecycle.map(([state,title],i)=><a key={state} href={'#how'} onClick={e=>{if(enabled){e.preventDefault();const box=document.getElementById('how');if(box)window.scrollTo({top:box.offsetTop+(box.offsetHeight-innerHeight)*((i+.2)/5),behavior:'smooth'});}}} className={i<=step?'active':''}><span>0{i+1}</span><strong>{title}</strong><i/></a>)}</div></div></section>
 <section className="cinema-boundaries"><div className="cinema-section-head"><Label>POWER, WITH BOUNDARIES.</Label><Link href="/docs/fees">FEES & LIMITS ↗</Link></div><div className="limit-editorial">{[['$1,000','PER PAYMENT'],['$5,000','PER AGENT / DAY'],['≤5%','RUNNER FEE CAP'],['1%','PROTOCOL FEE'],['24h','DISPUTE WINDOW']].map(([value,label],i)=><div data-cinema-reveal key={label}><span>0{i+1}</span><strong>{value}</strong><small>{label}</small></div>)}</div></section>
 <section className="cinema-privacy"><div className="privacy-word" aria-hidden="true">IN YOUR CONTROL.</div><div className="cinema-section-head"><Label>03 / PRIVACY IN PERSPECTIVE</Label><Shield size={21}/></div><div className="cinema-heading-pair"><h2 data-cinema-reveal>Every connection.<br/><em>A different view.</em></h2><p>Keep recipient details with the people who need them. Explore what each participant can see, including what stays public onchain.</p></div><div data-cinema-reveal>{privacy}</div><Link className="cinema-small-link" href="/scan">Inspect your onchain footprint <ArrowUpRight size={18}/></Link></section>
 <section className="cinema-developers"><div className="cinema-section-head"><Label>04 / MADE FOR MACHINE INTENT</Label><Code2 size={22}/></div><h2 data-cinema-reveal>Less friction.<br/><em>More possibility.</em></h2><div className="cinema-dev-grid"><div><p>TypeScript. HTTP. MCP.<br/>One payment interface, in the language your agent already speaks.</p><div className="interface-list"><span>01 / Inspect payment rails</span><span>02 / Set owner guardrails</span><span>03 / Prepare the last mile</span></div><Action href="/dev">Build with Rello</Action></div><div data-cinema-reveal>{code}</div></div></section>
 <section className="cinema-human"><div className="human-moving-type" aria-hidden="true"><div>THE HUMAN LAYER. THE HUMAN LAYER.</div></div><Label>05 / RUN THE LAST MILE</Label><h2 data-cinema-reveal>Your apps.<br/>Your limits.<br/><em>Your fee.</em></h2><div className="human-bottom"><p>Choose jobs on the apps you use. Check funding, carry out the payment, keep the proof, and follow the USDG settlement process.</p><Action href="/run">Become a runner</Action></div><div className="human-lines"><span>CHOOSE YOUR RAILS</span><span>VERIFY ESCROW</span><span>KEEP THE PROOF</span><span>SETTLE IN USDG</span></div></section>
 <section className="cinema-questions"><div><Label>THE DETAILS MATTER</Label><h2>Clarity.<br/><em>Built in.</em></h2><Link href="/docs" className="cinema-small-link">Read the documentation <ArrowUpRight size={18}/></Link></div><div className="faqs">{faq.slice(0,7).map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>
 <section className="cinema-end"><video src="/assets/cinema-vortex.mp4" poster="/assets/cinema-vortex.jpg" muted loop playsInline preload="none"/><div className="end-shade"/><Label>THE NEXT CONNECTION IS YOURS.</Label><div className="end-word" aria-hidden="true">GO<br/><em>BEYOND.</em></div><h2>Give your agent<br/>the last mile.</h2><div className="end-actions"><Action href="/agents">Open agent console</Action><Action href="/run" outline>Enter runner workspace</Action></div><a className="cinema-small-link" href="#top">BACK TO THE SURFACE ↑</a></section>
 </div>;
}
